# 应用服务 WEB 访问端口
server:
  port:8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: scott
    password: 123456

pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-args: true
  params: count=ROW_NUMBER


file:
  input-dir: "d:/code/input/"          # 输入文件目录
  output-dir: "d:/code/output/"        # 输出结果目录
  completed-dir: "d:/code/completed/"  # 已完成文件目录

# 定时任务配置
task:
  schedule:
    fixed-rate: 60000  # 每分钟执行一次